language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run test

deploy:
  provider: npm
  email: ajainvivek07@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
    tags: true
    repo: ajainvivek/preact-fluid

branches:
  only: master