language: node_js

node_js:
  - "10"

branches:
  only: master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run test

before_deploy: npm run build

deploy:
  provider: npm
  email: ajainvivek07@gmail.com
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: master
    repo: ajainvivek/preact-fluid